Import('env')

source = ['message.c']

static_lib = env.StaticLibrary('message', source)
shared_lib = env.SharedLibrary('message', source)

# copy file to 'release'
env.Command("../release/" + str(static_lib[0]), static_lib, Copy("$TARGET", "$SOURCE"))
env.Command("../release/" + str(shared_lib[0]), shared_lib, Copy("$TARGET", "$SOURCE"))
# copy file to 'test'
env.Command("../test/" + str(static_lib[0]), static_lib, Copy("$TARGET", "$SOURCE"))
env.Command("../test/" + str(shared_lib[0]), shared_lib, Copy("$TARGET", "$SOURCE"))
# copy shared library to 'root'
env.Command("../../" + str(shared_lib[0]), shared_lib, Copy("$TARGET", "$SOURCE"))



#env.Install("/usr/lib", [static_lib, shared_lib])
#env.Alias('install', ['/usr/lib'])
